name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release VSCode Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for semantic-release to analyze commit history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use a Long Term Support version of Node.js

      - name: Install dependencies
        run: npm ci # Use ci for faster, more reliable builds in CI

      - name: Compile TypeScript
        run: npm run compile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }} # Personal Access Token for VS Code Marketplace
        run: npx semantic-release 